#!/usr/bin/env perl

BEGIN {
  use FindBin;
  if ( -f "$FindBin::Bin/Makefile.PL" ) {
    use lib "$FindBin::Bin/lib";
  }
}

use warnings;
use strict;

use App::Tack;
App::Tack::run( shift(@ARGV), @ARGV );
